---
main:
  cluster_tool: DBSCAN
  faa_suffix: .faa
  gff_suffix: .gff
  fna_suffix: .fna
DBSCAN:
  cluster_eps: 4
  cluster_min_samples: 2
blast:
  blast_query: genes.fa
  blast_exec: blastp
  blast_threads: 1
  evalue: 1e-3
  ident_pct: 66

---
name: Equol Gene Cluster
components:
- name: Equol Production Pathway
  presence: essential
  components:
  - queryID: DZNR
    description: Daidzein reductase
    presence: essential
    terms:
    - id: GCF_000422625.1_00041
      method: blast
  - queryID: DHDR
    description: Dihydrodaidzein reductase
    presence: essential
    terms:
    - id: GCF_000422625.1_00043
      method: blast
  - queryID: THDR
    description: Tetrahydrodaidzein reductase
    presence: essential
    terms:
    - id: GCF_000422625.1_00044
      method: blast
  - queryID: DDRC
    description: Dihydrodaidzein racemase
    presence: essential
    terms:
    - id: GCF_000422625.1_00047
      method: blast
- name: fix electron transport
  presence: nonessential
  components:
  - queryID: FIXA
    description: fixA homolog
    presence: essential
    terms:
    - id: GCF_000422625.1_00046
      method: blast
  - queryID: FIXB
    description: fixB homolog
    presence: essential
    terms:
    - id: GCF_000422625.1_00045
      method: blast
  - queryID: FIXC
    description: fixC homolog
    presence: essential
    terms:
    - id: GCF_000422625.1_00040
      method: blast
  - queryID: FIXX
    description: fixX homolog
    presence: essential
    terms:
    terms:
    - id: GCF_000422625.1_00039
      method: blast
- name: hydrogenase maturase
  presence: nonessential
  components:
  - queryID: NADO
    descrition: NADH Oxidoreductase homolog
    presence: nonessential
    terms:
    - id: GCF_000422625.1_00038
      method: blast
  - queryID: HNDD
    description: Putative NADP-reducing hydrogenase subunit hndD
    presence: nonessential
    terms:
    - id: GCF_000422625.1_00037
      method: blast
  - queryID: HYDE
    description: putative hydrogenase maturase gene hydE
    presence: essential
    terms:
    - id: GCF_000422625.1_00036
      method: blast
  - queryID: HYDG
    description: putative hydrogenase maturase gene hydG
    presence: essential
    terms:
    - id: GCF_000422625.1_00035
      method: blast
  - queryID: HYDF
    description: putative hydrogenase maturase gene hydF
    presence: essential
    terms:
    - id: GCF_000422625.1_00034
      method: blast
- name: other genes
  presence: nonessential
  components:
  - queryID: HYPO
    description: Hypothetical Protein
    presence: nonessential
    terms:
    - id: GCF_000422625.1_00042
      method: blast
  - queryID: DEVR
    description: Putative devR transcriptional regulator
    presence: essential
    terms:
    - id: GCF_000422625.1_00048
      method: blast
