---
main:
  cluster_tool: DBSCAN
  faa_suffix: .faa
  gff_suffix: .gff
  fna_suffix: .fna
DBSCAN:
  cluster_eps: 4
  cluster_min_samples: 2
kofamscan:
  annot_suffix: .kofam.tsv
  threshold: 0.5

---
name: Equol Gene Cluster
components:
- name: Equol Production Pathway
  presence: essential
  components:
  - geneID: DZNR
    description: Daidzein reductase
    presence: essential
    terms:
    - id: K00219
      method: kofamscan
  - geneID: DHDR
    description: Dihydrodaidzein reductase
    presence: essential
    terms:
    - id: K18009
      method: kofamscan
  - geneID: THDR
    description: Tetrahydrodaidzein reductase
    presence: essential
    terms:
    - id: K00244
      method: kofamscan
  - geneID: DDRC
    description: Dihydrodaidzein racemase
    presence: essential
    terms:
    - id: K05606
      method: kofamscan
- name: fix electron transport
  presence: nonessential
  components:
  - geneID: FIXA
    description: fixA homolog
    presence: essential
    terms:
    - id: K03521
      method: kofamscan
  - geneID: FIXB
    description: fixB homolog
    presence: essential
    terms:
    - id: K03522
      method: kofamscan
  - geneID: FIXC
    description: fixC homolog
    presence: essential
    terms:
    - id: K00313
      method: kofamscan
  - geneID: FIXX
    description: fixX homolog
    presence: essential
    terms:
    - id: K03855
      method: kofamscan
- name: hydrogenase maturase
  presence: nonessential
  components:
  - geneID: NADO
    descrition: NADH Oxidoreductase homolog
    presence: nonessential
    terms:
    - id: K15022
      method: kofamscan
  - geneID: HNDD
    description: Putative NADP-reducing hydrogenase subunit hndD
    presence: nonessential
    terms:
    - id: K18332
      method: kofamscan
  - geneID: HYDE
    description: putative hydrogenase maturase gene hydE
    presence: essential
    terms:
    - id: K01012
      method: kofamscan
  - geneID: HYDG
    description: putative hydrogenase maturase gene hydG
    presence: essential
    terms:
    - id: K03150
      method: kofamscan
  - geneID: HYDF
    description: putative hydrogenase maturase gene hydF
    presence: essential
    terms:
    - id: K03977
      method: kofamscan
- name: other genes
  presence: nonessential
  components:
  - geneID: HYPO
    description: Hypothetical Protein
    presence: nonessential
    terms:
    - id: K02004
      method: kofamscan
  - geneID: DEVR
    description: Putative devR transcriptional regulator
    presence: essential
    terms:
    - id: K07695
      method: kofamscan
